export default {
  wordsList: [
    'CODE',
    // 'PROGRAMMATION',
    // 'GENTILHOMME',
    // 'HERMETIQUE',
    // 'TRAMPOLINE',
    // 'SCAPHANDRE',
    // 'SOULEVEMENT',
    // 'ARCHITECTURE',
    // 'ELECTROMENAGER',
    // 'MONGOLFIERE',
    // 'AVERTISSEMENT',
    // 'DESTRUCTURATION',
    // 'PASSEPORT',
    // 'VETERINAIRE',
    // 'INTELLIGENCE',
    // 'NUCLEAIRE',
    // 'TERASSEMENT',
    // 'AUBERGINE',
    // 'MAMMIFERE',
    // 'ROUCOULER',
    // 'REPUTATION',
    // 'MALHEUREUX',
    // 'POIGNARDER',
    // 'CONTAMINATION',
  ]
};
